# Base image
FROM node:18

# Direktori kerja di dalam container
WORKDIR /app

# Copy package.json dan package-lock.json
COPY package*.json ./

# Install dependencies, termasuk sequelize-cli secara global di dalam container
RUN npm install
RUN npm install -g sequelize-cli

# Copy sisa file aplikasi
COPY . .

# Expose port
EXPOSE 5000

# Command untuk menjalankan aplikasi
CMD ["npm", "run", "dev"]
